name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew shadowJar --nodaemon

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: Upload versions
          path: |
            v1_16-combat/build/libs/*.jar
            v1_19/build/libs/*.jar