name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build dependencies
        run: ./gradlew shadowJar --no-daemon

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Copy artifacts
        run: |
          cp v1_16-combat/build/libs/v1_16-combat-1.0.jar 1.16-combat-6.jar
          cp v1_19/build/libs/v1_19-1.0.jar 1.19.4.jar
          cp v1_20_6/build/libs/v1_20_6-1.0.jar 1.20.6.jar
          
          cp v1_16-combat/build/libs/v1_16-combat-1.0-all.jar 1.16-combat-6-deps.jar
          cp v1_19/build/libs/v1_19-1.0-all.jar 1.19.4-deps.jar
          cp v1_20_6/build/libs/v1_20_6-1.0-all.jar 1.20.6-deps.jar

      - name: Merge artifacts
        run: ./gradlew mergeJars --no-daemon

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: Versions
          path: |
            1.16-combat-6.jar
            1.19.4.jar
            1.20.6.jar