name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew shadowJar

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: Upload versions
          path: |
            v1_16-combat/build/libs/
            v1_19/build/libs/