name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Before build
        run: ./gradlew removeAll

      - name: Build dependencies
        run: ./gradlew shadowJar

      - name: Build
        run: ./gradlew build

      - name: Merge artifacts
        run: ./gradlew mergeJars

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: Versions
          path: |
            1.16-combat-6.jar
            1.19.4.jar
            1.20.1.jar
            1.20.6.jar
            1.21.1.jar